import httpx
import logging
from typing import Optional
from src.config import settings
from src.models.pubmed_dto import AlignedResultDTO

logger = logging.getLogger(__name__)


class PubmedClient:
    def __init__(self, base_url: Optional[str] = None, timeout: Optional[float] = None):
        self.base_url = (base_url or settings.pubmed_integration_url).rstrip("/")
        self.timeout = timeout or settings.pubmed_timeout_seconds

    async def get_aligned_results(self, pipeline_id: str, user_id: str) -> AlignedResultDTO:
        """
        Queries preliminary alignment results generated by pubmed-integration.
        Endpoint: GET /pubmed/aligned-results/{pipelineId}
        Requires the 'x-user-id' header for user session tracking.
        """
        url = f"{self.base_url}/pubmed/aligned-results/{pipeline_id}"
        logger.info(f"Querying aligned-results at: {url} with x-user-id: {user_id}")

        headers = {"x-user-id": user_id}

        async with httpx.AsyncClient(timeout=self.timeout) as client:
            try:
                response = await client.get(url, headers=headers)
                response.raise_for_status()
                data = response.json()
                return AlignedResultDTO.model_validate(data)
            except httpx.HTTPStatusError as e:
                logger.error(f"HTTP error {e.response.status_code} querying pubmed-integration: {e.response.text}")
                raise
            except httpx.RequestError as e:
                logger.error(f"Connection error with pubmed-integration ({url}): {str(e)}")
                raise
